// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdb_6Pk5LWmMlf0i9UZfKqfI4Vl_hxQ5E',
    appId: '1:660871350723:web:97f3eb1decd8fc34a41576',
    messagingSenderId: '660871350723',
    projectId: 'homeshop-a864',
    authDomain: 'homeshop-a864.firebaseapp.com',
    storageBucket: 'homeshop-a864.firebasestorage.app',
    measurementId: 'G-R7QNQFK23P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKe9bbyrxf0st2_tMv7YTGLpl4wmhjXgE',
    appId: '1:660871350723:android:3abe02961a9a8a6ba41576',
    messagingSenderId: '660871350723',
    projectId: 'homeshop-a864',
    storageBucket: 'homeshop-a864.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmI-lQ0LrP83Jq-Gm4jhktJWdaeIRPXfc',
    appId: '1:660871350723:ios:baec23ef4318d07fa41576',
    messagingSenderId: '660871350723',
    projectId: 'homeshop-a864',
    storageBucket: 'homeshop-a864.firebasestorage.app',
    iosBundleId: 'project.com.project',
  );
}
